### ISSUE TITLE
Cancel-Buttonn

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#65] opened 2022-03-27 16:02 UTC
Hello,

Can you create a Button, who i can Cancel the Download?

thx

Naim

**Comment by nbr23** [comment] 2022-03-27 21:34
Hi @Naimkr27,

Today it's not possible, but that's something I'm working on and should be doable soon.

Thanks!

**Comment by xnaas** [comment] 2022-05-29 07:44
This is a duplicate of #29, no?

**Closed** 2022-07-23 18:54 UTC
