### ISSUE TITLE
New error in download

### ISSUE THREAD

**Issue by PDSCi996** [nbr23/youtube-dl-server#34] opened 2021-02-13 16:58 UTC
I'm sorry to bother you again.
Today, a new error occurred when I used flexget to push YouTube videos. The following is the code. I directly grabbed two pictures.

This is the video address where the first error occurred.“

https://www.youtube.com/watch?v=Q_Ci9v4Z-hk”

![2021-02-14_004921](https://user-images.githubusercontent.com/50539888/107855624-8575c080-6e5e-11eb-88d5-0744533a14e1.jpg)

This is the second address“

https://www.youtube.com/watch?v=_qmccRF4-_E”

![2021-02-14_004408](https://user-images.githubusercontent.com/50539888/107855583-45aed900-6e5e-11eb-9b21-05e406b7b613.jpg)

**Comment by PDSCi996** [comment] 2021-02-16 17:43
I had another case of the same error today. I clicked to retry and it was useless. Later, I searched youtube and found the address of the video. After copying and pasting into the container, it can be downloaded normally. Is it because the format parameter is null?

**Comment by nbr23** [comment] 2021-02-17 01:01
Strange, I am not having any issues. It is not linked to the format being null, that issue was fixed a while ago.
Have you tried updating the youtube-dl version (click on the version number at the bottom of the page)?
![image](https://user-images.githubusercontent.com/1313493/108141432-9e2ee200-70bb-11eb-8b74-253de8067476.png)

**Comment by PDSCi996** [comment] 2021-02-17 04:05
Hello, I use flexget to push, the specific parameters are`curl -X POST --data-urlencode "url={{url}}" http://{{host}}:8080/youtube-dl/q
`，What youtube-dl receives is only the address but no video format parameters. I don’t know if the format parameters can be added directly to the curl command to solve the problem.

**Comment by PDSCi996** [comment] 2021-02-20 15:17
I’m here to trouble you again. Today, I copied and pasted a new video from YouTube manually. An error occurred. The address is "https://www.youtube.com/watch?v=URBF93oWN5s", and the error message says to open "--verbose" Parameter, I added this parameter and got the following error code. It has been confirmed repeatedly that my youtube-dl is the latest version and there is no problem with the network.
Hope it helps to perfect the container.

```Error during download task:
Exception:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--output', '/youtube-dl/%(uploader)s/%(title)s.%(ext)s', '--cache-dir', '/youtube-dl/.cache', '--ignore-errors', '--age-limit', '6', '--format', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--geo-bypass', '--abort-on-unavailable-fragment', '--playlist-end', '1000', '--match-filter', '! is_live', '--playlist-reverse', '--merge-output-format', 'mp4', '--recode-video', 'mp4', '--write-sub', '--write-auto-sub', '--sub-lang', 'zh-CN,zh-TW,zh-Hans,zh,en,jp', '--sub-format', 'srt', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--verbose', 'https://www.youtube.com/watch?v=URBF93oWN5s', '-J', '--flat-playlist']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.9.1 (CPython) - Linux-3.10.105-x86_64-with
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1632, in _real_extract
self._sort_formats(formats)
File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by PDSCi996** [comment] 2021-02-21 10:48
There have been new errors in the last few days and I have posted them all together, hoping to help improve the container.
The first one is to download the video "https://www.youtube.com/watch?v=drVY5gymo0g" today, prompting an error code，
![错误1](https://user-images.githubusercontent.com/50539888/108622294-c4190580-7472-11eb-806c-b4184197cc1e.jpg)
Then I changed the parameter "LANG=C.UTF=8" to "LANG=zh_CN.UTF-8". After restarting the container, youtube automatically upgrades and prompts an error. The code is as follows
![升级1](https://user-images.githubusercontent.com/50539888/108622359-40abe400-7473-11eb-9a15-f23e3e6ba469.jpg)
I clicked "Failed/Retry", the download is still wrong after retrying, the code is as follows
![错误2](https://user-images.githubusercontent.com/50539888/108622467-0131c780-7474-11eb-821d-b5969de35925.jpg)
The file type at this time is "null", "https://www.youtube.com/watch?v=drVY5gymo0g" this address is automatically pushed by "flexget", I manually fill in this address into the container download bar and proceed Everything is normal after downloading. At this time, the file type is displayed as "video/best" and the code is as follows.
![正常1](https://user-images.githubusercontent.com/50539888/108622660-40ace380-7475-11eb-90f4-306b979e8992.jpg)

**Comment by nbr23** [comment] 2021-02-28 16:48
Hi @PDSCi996,

So there was definitely an issue when submitting a video without the format, if that download failed and you hit "retry", it would get confused and not find the format. This is fixed with https://github.com/nbr23/youtube-dl-server/commit/c8ac2fe94a5bee12121e83c25426ba1e1c59bec7

However the rest of your issues, I am not able to reproduce.
My encoding is utf-8 and I have no issues downloading https://www.youtube.com/watch?v=drVY5gymo0g
Can you share your latest configuration file so that I try again with the exact same config as you?

Thanks!

**Comment by PDSCi996** [comment] 2021-03-02 12:13
The following is my specific configuration. My main application is to use in a Chinese environment. I don’t actually know what utf-8 is. I have found a way to add format parameters in flashget. I haven’t changed all the details yet. Today Just make a change and test it tomorrow.
Thank you again for your hard work.


```ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: False    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/youtube-dl/%(playlist)s/%(title)s.%(ext)s' # Playlist output directory template
  update_poll_delay_min: 1440 # Automatically check for updates every 24h
  max_log_entries: 100 # Maximum number of job log history to keep
  forwarded_allow_ips: None # uvicorn Comma seperated list of IPs to trust with proxy headers.
  proxy_headers: True # uvicorn flag Enable/Disable X-Forwarded-Proto, X-Forwarded-For, X-Forwarded-Port to populate remote address info.

ydl_options:  # youtube-dl options
  output: '/youtube-dl/%(uploader)s/%(title)s.%(ext)s' # output directory template
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  age-limit: 6 # minimal age requirement / parental control setting
  format:  bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best 
  geo-bypass: True
  abort-on-unavailable-fragment: True
  playlist-end: 1000
  match-filter: "! is_live"
  playlist-reverse: True
  merge-output-format: mp4
  recode-video: mp4
  #write-thumbnail: True
  write-sub: True
  write-auto-sub: True
  sub-lang: zh-CN,zh-TW,zh-Hans,zh,en,jp
  #all-subs: True
  sub-format: srt
  embed-subs: True
  embed-thumbnail: True
  add-metadata: True
  #convert-subs: srt # zhuan huan zi mu ge shi 
  verbose: True```

**Comment by PDSCi996** [comment] 2021-03-07 12:12
Hello, there was a new error today. I downloaded a new YouTube video with the address "https://www.youtube.com/watch?v=hUq-mHlq5Fk". Below is the error code. I think the prompt seems to be Said the file name is too long.
![错误代码](https://user-images.githubusercontent.com/50539888/110239328-52b47900-7f81-11eb-8bc7-bbeb192c5aad.jpg)

**Comment by blackerking** [comment] 2021-06-10 13:06
@PDSCi996 
Since PCs became a thing name and character save and display is a common problem.
UTF-8 or UTF-16 makes it possible to save and display most used languages.
Suddenly not all applications nor every OS is capable of using these charactersettings.

Maybe the youtube-dl standard (gui-less) version is better for you're usage.

Otherwise it could broke different things. In case some filesystems can't handle the filenames correctly bad things will happen.

**Closed** 2023-05-06 22:00 UTC
